import 'dotenv/config'

export const env = {
  PORT : process.env.PORT,
  HOST_NAME : process.env.HOST_NAME,
  MONGODB_URI : process.env.MONGODB_URI,
  DATABASE_NAME: process.env.DATABASE_NAME,
  BUILD_MODE : process.env.BUILD_MODE,
  WEBSITE_DOMAIN_DEVELOPMENT : process.env.WEBSITE_DOMAIN_DEVELOPMENT,
  WEBSITE_DOMAIN_PRODUCTION : process.env.WEBSITE_DOMAIN_PRODUCTION,
  MAILER_SEND_API_KEY : process.env.MAILER_SEND_API_KEY,
  ADMIN_SENDER_EMAIL : process.env.ADMIN_SENDER_EMAIL,
  ADMIN_SENDER_NAME : process.env.ADMIN_SENDER_NAME,
  ACCESS_TOKEN_SECRET_SIGNATURE : process.env.ACCESS_TOKEN_SECRET_SIGNATURE,
  ACCESS_TOKEN_LIFE : process.env.ACCESS_TOKEN_LIFE,
  REFRESH_TOKEN_SECRET_SIGNATURE : process.env.REFRESH_TOKEN_SECRET_SIGNATURE,
  REFRESH_TOKEN_LIFE : process.env.REFRESH_TOKEN_LIFE
}