import 'dotenv/config'

export const env = {
  PORT : process.env.PORT,
  HOST_NAME : process.env.HOST_NAME,
  MONGODB_URI : process.env.MONGODB_URI,
  DATABASE_NAME: process.env.DATABASE_NAME,
  BUILD_MODE : process.env.BUILD_MODE,
  WEBSITE_DOMAIN_DEVELOPMENT : process.env.WEBSITE_DOMAIN_DEVELOPMENT,
  WEBSITE_DOMAIN_PRODUCTION : process.env.WEBSITE_DOMAIN_PRODUCTION,

  ACCESS_TOKEN_SECRET_SIGNATURE : process.env.ACCESS_TOKEN_SECRET_SIGNATURE,
  ACCESS_TOKEN_LIFE : process.env.ACCESS_TOKEN_LIFE,
  REFRESH_TOKEN_SECRET_SIGNATURE : process.env.REFRESH_TOKEN_SECRET_SIGNATURE,
  REFRESH_TOKEN_LIFE : process.env.REFRESH_TOKEN_LIFE,

  EMAIL_HOST : process.env.EMAIL_HOST,
  EMAIL_PORT : process.env.EMAIL_PORT,
  EMAIL_FROM : process.env.EMAIL_FROM,
  EMAIL_FROM_NAME : process.env.EMAIL_FROM_NAME,
  EMAIL_PASS : process.env.EMAIL_PASS,

  CLOUDINARY_CLOUD_NAME : process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY : process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET : process.env.CLOUDINARY_API_SECRET
}